### ISSUE TITLE
what's this?help。。

### ISSUE THREAD

**Issue by Akrayter** [SamsungLabs/TwiTi#2]
t_total value of -1 results in schedule not being applied
Killed

**Comment by chen1602** [comment]
got same error dont know what is that yet

**Comment by Akrayter** [comment]
Do you need this project, too? We can talk together. I've been working on this project for days

**Comment by Akrayter** [comment]
i need some help...

**Comment by chen1602** [comment]
I succedded complete the build of the ner :)
In the file "C:\Program Files\Python39\Lib\site-packages\torch\nn\functional.py"
add line 2264 - 
target = target.type(torch.long) 
add line 1852 - 
input = input.type(torch.LongTensor)

I don't know if it is the solution now ill try to run the project

**Comment by chen1602** [comment]
Now the project seems to run on my computer. I havent tried to use it but the commands in the README executed fine

**Comment by Akrayter** [comment]
> I succedded complete the build of the ner :)
> In the file "C:\Program Files\Python39\Lib\site-packages\torch\nn\functional.py"
> add line 2264 -
> target = target.type(torch.long)
> add line 1852 -
> input = input.type(torch.LongTensor)
> 
> I don't know if it is the solution now ill try to run the project

but i run it on centos,i don't know wh

**Comment by Akrayter** [comment]
> Now the project seems to run on my computer. I havent tried to use it but the commands in the README executed fine

I particularly want to know what happens when the program runs properly，I think you'll need a JSON file to test it

**Comment by Akrayter** [comment]
> 我成功完成了 ner 的构建 :)
> 在文件“C:\Program Files\Python39\Lib\site-packages\torch\nn\functional.py”中
> 添加第 2264 行 -
> target = target.type(torch.long)
> 添加第 1852 行 -
> input = input.type(torch.LongTensor)
> 
> 我不知道这是否是现在尝试运行该项目的解决方案

I added the code according to your method, but that problem still appears

**Comment by chen1602** [comment]
The code i added is at the torch module it self under nn\functional.py.
U should run the build and see if u get error at the same points i got them.
The tool itself gets tweets as u wrote, extracts the iocs and classify them.

**Comment by Akrayter** [comment]
> 我添加的代码位于 nn\functional.py 下的 Torch 模块中。
> 你应该运行构建，看看你是否在我得到它们的同一点得到错误。
> 该工具本身会在您编写时获取推文，提取 ioc 并对它们进行分类。

I added the code according to your method, but it did not solve the problem of Killed after ner was constructed. I was never able to build ner correctly.

**Comment by Akrayter** [comment]
> > 我添加的代码位于 nn\functional.py 下的 Torch 模块。
> > 你应该运行，你是否在我得到它们的相同点得到
> > 该工具会在你看照片时获取推文，提取 ioc 并对它们进行分类。
> 
> 我按照你的方法加了代码，但是没有解决ner构建后Killed的问题。我永远无法正确构建 ner。

I know that the program automatically extracts IOC from tweets and classifies them. I would like to know if you can normally use NER to extract IOC after completing the construction of NER

**Comment by summernote5288** [comment]
> The code i added is at the torch module it self under nn\functional.py.
> U should run the build and see if u get error at the same points i got them.
> The tool itself gets tweets as u wrote, extracts the iocs and classify them.

Hello, I would like to ask how this tool can get json format tweets by itself?

**Comment by Akrayter** [comment]
> > The code i added is at the torch module it self under nn\functional.py.
> > U should run the build and see if u get error at the same points i got them.
> > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> 
> Hello, I would like to ask how this tool can get json format tweets by itself?

You can actually get the JSON format of tweets via Twitter's own API or through other tools

**Comment by Akrayter** [comment]
> The code i added is at the torch module it self under nn\functional.py.
> U should run the build and see if u get error at the same points i got them.
> The tool itself gets tweets as u wrote, extracts the iocs and classify them.

Hi buddy, can you give me more information on how this project was built? I still can't run it fully

**Comment by summernote5288** [comment]
> > The code i added is at the torch module it self under nn\functional.py.
> > U should run the build and see if u get error at the same points i got them.
> > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> 
> Hi buddy, can you give me more information on how this project was built? I still can't run it fully

I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.

**Comment by summernote5288** [comment]
> > > The code i added is at the torch module it self under nn\functional.py.
> > > U should run the build and see if u get error at the same points i got them.
> > > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> > 
> > 
> > Hi buddy, can you give me more information on how this project was built? I still can't run it fully
> 
> I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.



> > > The code i added is at the torch module it self under nn\functional.py.
> > > U should run the build and see if u get error at the same points i got them.
> > > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> > 
> > 
> > Hi buddy, can you give me more information on how this project was built? I still can't run it fully
> 
> I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.

**This is the JSON text content that needs to be predicted：**
[{
	"full_text": "Some maybe new WARPRISM dropping BEACON\nhttps://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036...",
	"entities" : {
		"urls":[]
}
},
{
	"full_text": "#Trickbot\n162[.]248[.]225[.]122\n\nhttps://www.virustotal.com/gui/ip-address/162.248.225.122/summary\n\nMalDoc distribution: https://t.co/gSNAo...",
	"entities" : {
		"urls":[]
}
}]
**and this is what the program predicted：**
[{"iocs": {"hashes": {"sha1": [], "sha256": ["a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "md5": []}, "ips": [], "urls": {"urls": ["https://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "domain": []}}, "entities": [], "context": [], "externals": []},

 {"iocs": {"hashes": {"sha1": [], "sha256": [], "md5": []}, "ips": ["162.248.225.122"], "urls": {"urls": ["https://www.virustotal.com/gui/ip-address/162.248.225.122/summary"], "domain": []}}, "entities": [], "context": [], "externals": []}]
**It looks not bad**

**Comment by Akrayter** [comment]
> Some may new WARPRISM drop BEACON\nhttps://www.virustotal.com/gui/file/a8

Thank you for your information. I guess it is due to the problem of my graphics card driver that I cannot build the model correctly. I would like to ask if you are running this project on the Windows platform? And I read in the author's paper that this program should have more functions.

**Comment by Akrayter** [comment]
> > > > The code i added is at the torch module it self under nn\functional.py.
> > > > U should run the build and see if u get error at the same points i got them.
> > > > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> > > 
> > > 
> > > Hi buddy, can you give me more information on how this project was built? I still can't run it fully
> > 
> > 
> > I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.
> 
> > > > The code i added is at the torch module it self under nn\functional.py.
> > > > U should run the build and see if u get error at the same points i got them.
> > > > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> > > 
> > > 
> > > Hi buddy, can you give me more information on how this project was built? I still can't run it fully
> > 
> > 
> > I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.
> 
> **This is the JSON text content that needs to be predicted：**
> [{
> "full_text": "Some maybe new WARPRISM dropping BEACON\nhttps://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036...",
> "entities" : {
> "urls":[]
> }
> },
> {
> "full_text": "#Trickbot\n162[.]248[.]225[.]122\n\nhttps://www.virustotal.com/gui/ip-address/162.248.225.122/summary\n\nMalDoc distribution: https://t.co/gSNAo...",
> "entities" : {
> "urls":[]
> }
> }]
> **and this is what the program predicted：**
> [{"iocs": {"hashes": {"sha1": [], "sha256": ["a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "md5": []}, "ips": [], "urls": {"urls": ["https://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "domain": []}}, "entities": [], "context": [], "externals": []},
> 
> {"iocs": {"hashes": {"sha1": [], "sha256": [], "md5": []}, "ips": ["162.248.225.122"], "urls": {"urls": ["https://www.virustotal.com/gui/ip-address/162.248.225.122/summary"], "domain": []}}, "entities": [], "context": [], "externals": []}]
> **It looks not bad**

This is my generated model_conf.json, is it the same as yours
{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

**Comment by summernote5288** [comment]
> > > > > The code i added is at the torch module it self under nn\functional.py.
> > > > > U should run the build and see if u get error at the same points i got them.
> > > > > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> > > > 
> > > > 
> > > > Hi buddy, can you give me more information on how this project was built? I still can't run it fully
> > > 
> > > 
> > > I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.
> > 
> > 
> > > > > The code i added is at the torch module it self under nn\functional.py.
> > > > > U should run the build and see if u get error at the same points i got them.
> > > > > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> > > > 
> > > > 
> > > > Hi buddy, can you give me more information on how this project was built? I still can't run it fully
> > > 
> > > 
> > > I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.
> > 
> > 
> > **This is the JSON text content that needs to be predicted：**
> > [{
> > "full_text": "Some maybe new WARPRISM dropping BEACON\nhttps://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036...",
> > "entities" : {
> > "urls":[]
> > }
> > },
> > {
> > "full_text": "#Trickbot\n162[.]248[.]225[.]122\n\nhttps://www.virustotal.com/gui/ip-address/162.248.225.122/summary\n\nMalDoc distribution: https://t.co/gSNAo...",
> > "entities" : {
> > "urls":[]
> > }
> > }]
> > **and this is what the program predicted：**
> > [{"iocs": {"hashes": {"sha1": [], "sha256": ["a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "md5": []}, "ips": [], "urls": {"urls": ["https://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "domain": []}}, "entities": [], "context": [], "externals": []},
> > {"iocs": {"hashes": {"sha1": [], "sha256": [], "md5": []}, "ips": ["162.248.225.122"], "urls": {"urls": ["https://www.virustotal.com/gui/ip-address/162.248.225.122/summary"], "domain": []}}, "entities": [], "context": [], "externals": []}]
> > **It looks not bad**
> 
> This is my generated model_conf.json, is it the same as yours
> {
> "attention_probs_dropout_prob": 0.1,
> "hidden_act": "gelu",
> "hidden_dropout_prob": 0.1,
> "hidden_size": 768,
> "initializer_range": 0.02,
> "intermediate_size": 3072,
> "max_position_embeddings": 512,
> "num_attention_heads": 12,
> "num_hidden_layers": 12,
> "type_vocab_size": 2,
> "vocab_size": 30522
> }

I have the same result as you

**Comment by Akrayter** [comment]
> > > > > > 我添加的代码位于 nn\functional.py 下的 Torch 模块中。
> > > > > > 你应该运行构建，看看你是否在我得到它们的同一点得到错误。
> > > > > > 该工具本身会在您编写时获取推文，提取 ioc 并对它们进行分类。
> > > > > 
> > > > > 
> > > > > 嗨，伙计，你能给我更多关于这个项目是如何构建的信息吗？我还是不能完全运行
> > > > 
> > > > 
> > > > 我更改了 ner/builder.py 中的第 325 行代码： loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)). 现在我可以build ner。但是好像数据集中的数据太少了，构建的ner无法预测好的结果。
> > > 
> > > 
> > > > > > 我添加的代码位于 nn\functional.py 下的 Torch 模块中。
> > > > > > 你应该运行构建，看看你是否在我得到它们的同一点得到错误。
> > > > > > 该工具本身会在您编写时获取推文，提取 ioc 并对它们进行分类。
> > > > > 
> > > > > 
> > > > > 嗨，伙计，你能给我更多关于这个项目是如何构建的信息吗？我还是不能完全运行
> > > > 
> > > > 
> > > > 我更改了 ner/builder.py 中的第 325 行代码： loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)). 现在我可以build ner。但是好像数据集中的数据太少了，构建的ner无法预测好的结果。
> > > 
> > > 
> > > **这是需要预测的 JSON 文本内容：** 
> > > [{ 
> > > "full_text": "Some may new WARPRISM drop BEACON\nhttps://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c9033f659c933 
> > > " { 
> > > "urls":[] 
> > > } 
> > > }, 
> > > { 
> > > "full_text": "#Trickbot\n162[.]248[.]225[.]122\n\nhttps://www.virustotal.com/gui/ip-address /162.248.225.122/summary\n\nMalDoc 分布：https://t.co/gSNAo...", 
> > > "entities" : { 
> > > "urls":[] 
> > > } 
> > > }]
> > > **这就是程序预测的：**
> > > [{"iocs": {"hashes": {"sha1": [], "sha256": ["a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036,"ips:"], "ips:", "] urls": ["https://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "domain": []"},"sentities,"external:"], []}, 
> > > {"iocs": {"hashes": {"sha1": [], "sha256": [], "md5": []}, "ips": ["162.248.225.122"], " urls": {"urls": ["https://www.virustotal.com/gui/ip-address/162.248.225.122/summary"], "domain": []}}, "entities": [], “上下文”：[]，“外部”：[]}]
> > > **看起来还不错**
> > 
> > 
> > 这是我生成的model_conf.json，和你的一样吗
> > { 
> > "attention_probs_dropout_prob": 0.1, 
> > "hidden_​​act": "gelu", 
> > "hidden_​​dropout_prob": 0.1, 
> > "hidden_​​size": 768, 
> > "initializer_range": 0.02, 
> > "intermediate_size" ：3072，
> > “max_position_embeddings”：512，
> > “num_attention_heads”：12，
> > “num_hidden_​​layers”：12，
> > “type_vocab_size”：2，
> > “vocab_size”：30522 
> > }
> 
> 我和你的结果一样

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/TwiTi/ioc_extractor/__main__.py", line 44, in <module>
    main()
  File "/root/TwiTi/ioc_extractor/__main__.py", line 33, in main
    tweets, args.expand_external
  File "/root/TwiTi/ioc_extractor/ioc_extract_manager.py", line 77, in ioc_extraction
    orig_text = tw['full_text']
TypeError: string indices must be integers

Why did this error occur。。。。。

**Comment by Akrayter** [comment]
I noticed that the Classfify module seems to be missing input files, so I can't run it. Anyone experiencing this problem

**Comment by CHIANCAN** [comment]
> > > > > > The code i added is at the torch module it self under nn\functional.py.
> > > > > > U should run the build and see if u get error at the same points i got them.
> > > > > > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> > > > > 
> > > > > 
> > > > > Hi buddy, can you give me more information on how this project was built? I still can't run it fully
> > > > 
> > > > 
> > > > I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.
> > > 
> > > 
> > > > > > The code i added is at the torch module it self under nn\functional.py.
> > > > > > U should run the build and see if u get error at the same points i got them.
> > > > > > The tool itself gets tweets as u wrote, extracts the iocs and classify them.
> > > > > 
> > > > > 
> > > > > Hi buddy, can you give me more information on how this project was built? I still can't run it fully
> > > > 
> > > > 
> > > > I changed the 325th line of code in ner/builder.py : loss = loss_fct(logits.view(-1, len(LABELS)), b_labels.view(-1).type(torch.long)).Now I can build ner.But it seems that there are too few data in the data set, and the constructed ner cannot predict good results.
> > > 
> > > 
> > > **This is the JSON text content that needs to be predicted：**
> > > [{
> > > "full_text": "Some maybe new WARPRISM dropping BEACON\nhttps://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036...",
> > > "entities" : {
> > > "urls":[]
> > > }
> > > },
> > > {
> > > "full_text": "#Trickbot\n162[.]248[.]225[.]122\n\nhttps://www.virustotal.com/gui/ip-address/162.248.225.122/summary\n\nMalDoc distribution: https://t.co/gSNAo...",
> > > "entities" : {
> > > "urls":[]
> > > }
> > > }]
> > > **and this is what the program predicted：**
> > > [{"iocs": {"hashes": {"sha1": [], "sha256": ["a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "md5": []}, "ips": [], "urls": {"urls": ["https://www.virustotal.com/gui/file/a85ce74c8fc41e1b88a5c85a35087e16123f41f3e22f69c923550ac43499c036"], "domain": []}}, "entities": [], "context": [], "externals": []},
> > > {"iocs": {"hashes": {"sha1": [], "sha256": [], "md5": []}, "ips": ["162.248.225.122"], "urls": {"urls": ["https://www.virustotal.com/gui/ip-address/162.248.225.122/summary"], "domain": []}}, "entities": [], "context": [], "externals": []}]
> > > **It looks not bad**
> > 
> > 
> > This is my generated model_conf.json, is it the same as yours
> > {
> > "attention_probs_dropout_prob": 0.1,
> > "hidden_act": "gelu",
> > "hidden_dropout_prob": 0.1,
> > "hidden_size": 768,
> > "initializer_range": 0.02,
> > "intermediate_size": 3072,
> > "max_position_embeddings": 512,
> > "num_attention_heads": 12,
> > "num_hidden_layers": 12,
> > "type_vocab_size": 2,
> > "vocab_size": 30522
> > }
> 
> I have the same result as you

方便留个联系方式吗，想请教一下搭建中的一下问题。

**Comment by FowlieRini** [comment]
@summernote5288 请问可以留个联系方式吗，想咨询一下使用中的问题，或者查看我主页，有我的邮箱。
